blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('',views.all_blogs,name='all_blogs'),
    path('<int:blog_id>/',views.detail,name='detail'),
]

mi_portfolio/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',views.home,name='home'),
    path('blog/', include('blog.urls')),
    path('about',views.about,name='about'),
    path('pasword',views.pasword,name='pasword'),
    path('your_pasword',views.your_pasword,name='your_pasword'),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class Blog(models.Model):
	title = models.CharField(max_length=200)
	text = models.TextField()
	date = models.DateField()
	image = models.ImageField(upload_to='blog/images')

	def __str__(self):
		return self.title

portfolio/models.py
from django.db import models

class Project(models.Model):
	title = models.CharField(max_length=100)
	description = models.CharField(max_length=250)
	image = models.ImageField(upload_to='porfolio/images')
	url = models.URLField(blank=True)

	def __str__(self):
		return self.title

blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import Blog

def all_blogs(request):
	blogs = Blog.objects.all()
	return render(request,'blog/all_blogs.html',{'blogs':blogs}) 

def detail(request,blog_id):
	blog = get_object_or_404(Blog,pk=blog_id)
	return render(request,'blog/detail.html',{'blog':blog})

portfolio/views.py
from django.shortcuts import render
from .models import Project
import random

def home(request):
	projects = Project.objects.all()
	return render(request,'portfolio/home.html',{'projects':projects})

def about(request):
	return render(request,'portfolio/about.html')

def pasword(request):
	return render(request,'portfolio/pasword_home.html')

def your_pasword(request):
    pasword = ''
    len = request.GET.get('lenght',12)
    character = list('qwertyuiopasdfghjklzxcvbnm')
    
    if request.GET.get('uppercase'):
        character.extend(list('QWERTYUIOPASDFGHJKLZXCVBNM'))
    if request.GET.get('nambers'):
        character.extend(list('1234567890'))
    if request.GET.get('special'):
        character.extend(list('!@#$%^&*()_'))
    for i in range(int(len)):
        pasword += random.choice(character)
    return render(request,'portfolio/your_pasword.html',{'pasword':pasword})

blog/templates/blog/all_blogs.html
{% extends 'portfolio/base.html' %}
{% block content %}
{% load static %}
<img src="{% static 'blog/lampa.jpg' %}" width="300" height="300" > 
<h1>Bulat has written {{ blogs.count }} blog{{ blogs.count|pluralize }}</h1>


{% for blog in blogs %}

<h2>{{ blog.title }}</h2>
<p>{{ blog.date|date:'l d m Y' }}</p>
<br>
<img src="{{ blog.image.url }}" width="500" alt="">
<br>

<a href="{% url 'blog:detail' blog.id %}"><h4>{{ blog.text|truncatechars:100 }}</h4></a>
<br>
<br>
{% endfor %}

{% endblock %}

blog/templates/blog/detail.html
{% extends 'portfolio/base.html' %}
{% block content %}

<h1>{{ blog.title }}</h1>

<h5>--{{ blog.date|date:'F jS Y' }}--</h5>
<img src="{{ blog.image.url }}" width="500" alt="">
<p>{{ blog.text }}</p>

{% endblock %}

portfolio/templates/portfolio/about.html
{% extends 'portfolio/base.html' %}

{% block content %}

<h1>About</h1>

<p>This is Mi portfolio created by Bulat Nitaliev Enjoy fam!</p>

{% endblock %}

portfolio/templates/portfolio/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <link rel="stylesheet" href="{% static "portfolio/custom.css" %}">

  <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">

  <link rel="icon" type="image/png" href="{% static "portfolio/Logo.png" %}">

  <title>Bulat Nitaliev</title>
</head>
<div class ="container text-center">
<body>

  <nav id="topNav" class="navbar navbar-expand-md navbar-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static "portfolio/Logo.png" %}" width="30" height="30" class="d-inline-block align-top" alt="Nick's Logo">
        <span>Bulat Nitaliev</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% static "portfolio/Ниталиев Булат.pdf" %}">Resume</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'about' %}" target="_blank">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}" target="_blank">Home</a>
          </li>
          <li>
            <a role="button" href="{% url 'blog:all_blogs' %}" class="btn btn-primary">Blog</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    {% block content %}{% endblock %}
  </div>
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

</html>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}
{% block content %}
{% load static %}
<h1>Bulat's portfolio :)</h1>

<img src="{% static 'portfolio/bulat.jpg' %}" alt="">
<br>
<br>
<a href="{% static 'portfolio/stepik-certificate-82541-d6ff393.pdf' %}"><h3>Certificate</h3></a>

{% for project in projects %}



<h3>{{ project.title }}</h3>
<p>{{project.description}}</p>
<a href="{% url 'pasword' %}"><img src="{{ project.image.url }}" alt=""></a>

{% endfor %}

<a href="{{ project.url }}">Link</a>

{% endblock %}

portfolio/templates/portfolio/pasword_home.html
{% extends 'portfolio/base.html' %}
{% block content %}
<div class="container text-center">
<h1>Pasword Generator</h1>
<form action = "{% url 'your_pasword' %}">
    <select name = 'lenght'>
        <option value-'6'>6</option>
        <option value-'7'>7</option>
        <option value-'8'>8</option>
        <option value-'9'>9</option>
        <option value-'10'>10</option>
        <option value-'11'>11</option>
        <option value-'12' selected='selected'>12</option>
        <option value-'13'>13</option>
        <option value-'14'>14</option>
    </select> Length
    <br>
    <input type='checkbox' name='uppercase'> Uppercase
    <br>
    <input type='checkbox' name='nambers'> Nambers
    <br>
    <input type='checkbox' name='special'> Special Characters
    <br>
    <input type='submit' value='Generate Pasword' class="btn btn-primary">
</form>

</div>

{% endblock %}

portfolio/templates/portfolio/your_pasword.html
{% extends 'portfolio/base.html' %}
{% block content %}

<div class ="container text-center">
<h1>Your pasword is:</h1>
<h2 class = "alert alert-success">{{ pasword }}</h2>

</div>
{% endblock %}